[package]
authors = ["Lucas Avila <lucaxx@gmail.com>"]
edition = "2024"
name = "beff_wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.106"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = {version = "0.1.7", optional = true}
beff-core = {version = "0.1.0", path = "../beff-core"}

console_log = "1.0.0"
js-sys = "0.3.64"
lazy_static = "1.4.0"

swc_common = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }